### PR TITLE
Script to create user manager accounts for CHIS KE

### PR DESCRIPTION
**Pull request by kennsippell**
#79 
Intended use for this script is to create { 25 users * 47 instances } = 1175 user manager accounts in CHIS KE production.

This script creates a user with `role: user_manager` within a given instance's county. For Siaya/Migori it supports county disambiguation. Check out `README.md` or run `npx ts-node scripts/create-user-managers/index.ts --help` to understand its use.

This is positioned well to support Uganda, but will require further updates once [this request](https://github.com/medic/config-ug-vht/issues/904#issuecomment-1946422120) has been fulfilled and requirements are more clear.

I've used base branches from https://github.com/medic/cht-user-management/pull/58 and https://github.com/medic/cht-user-management/pull/75 to avoid a tricky merge down the line. So will need one of those to merge before I send this for review. For the curious, all content for this PR is in `scripts/create-user-managers` and package.json.

### CODE REVIEW

**Comment by kennsippell** [comment]
Hey @paulpascal, This script isn't perfect but this is what I used to creation a few hundred user managers for eCHIS Kenya. I think it's worth reviewing and committing now and we can continue to iterate on it through issues and new PRs.  Can you take a look when you have time?

**Comment by paulpascal** [comment]
For Sure @kennsippell

**Review by paulpascal — APPROVED** [review]
Yay ! Nice

What about having a file-base input for (names, password, county) in future iteration ?

**Comment by kennsippell** [comment]
@paulpascal Yes!! Definitely. lol. It was a large pain actually...

**Pull request merged**
