### PR TITLE
Use user-settings docs for disableUsersWithPlace

### PR DESCRIPTION
**Pull request by kennsippell**
To test this, replace a user on eCHIS running CHT-core >4.4 logged in via [this user-manager role](https://github.com/moh-kenya/config-echis-2.0/pull/1808).

#76

### CODE REVIEW

**Comment by kennsippell** [comment]
Ping @alexosugo now that you're back from meetup

**Comment by alexosugo** [comment]
@kennsippell I've experienced some challenges testing this with the training instance due to multiple duplicate CHUs. I'm unable to proceed beyond filling the replacement form.

**Comment by kennsippell** [comment]
@alexosugo Training instances are running `4.2.2`, I believe. This will require `>4.4` to test, so training might not be the best place to test it. 

Also, I know you were having problems with login. This may have been related to https://github.com/medic/cht-user-management/issues/97 which is now fixed. I encourage you to test again and I would be happy to do a pair session with you if you get stuck.

**Review by alexosugo — APPROVED** [review]
Sorry it took a while. Tested and works great!

**Pull request merged**
