### PR TITLE
Support for Date of Birth inputs

### PR DESCRIPTION
**Pull request by kennsippell**
#31

Watch base branch when merging

image

* Validation, Formatting, UI date picker using Bulma datepicker

### CODE REVIEW

**Comment by kennsippell** [comment]
Feedback from @jonathanbataire 

> Dob should support just a number of years old and infer from today's date

**Review by freddieptf — APPROVED** [review]
LGTM. @jonathanbataire's feedback is valid and a simple number input reduces the clicks for the user but we sacrifice accuracy. I think the calendar widget should be fine and we can get more feedback from users after usage

**Comment by kennsippell** [comment]
@jonathanbataire Thoughts?

**Comment by jonathanbataire** [comment]
> @jonathanbataire Thoughts?

it should support both age as a number eg 37 and DoB in the `yyyy-mm-dd` format at least in the generated json
for age once someone submits a number (37) we can use today's date to calculate dob and save that dob in the json
support age because some people have no idea when their dob is but can tell their age

**Comment by kennsippell** [comment]
Waiting for #40 before merging

**Pull request merged**
